# Generated by Django 5.1.4 on 2025-01-02 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_remove_user_bio_user_login_provider_refreshtoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='login_provider',
            field=models.CharField(blank=True, choices=[('GOOGLE', 'GOOGLE'), ('GITHUB', 'GITHUB'), ('DISCORD', 'DISCORD'), ('NO_PROVIDER', 'NO PROVIDER')], default='NO_PROVIDER', max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='RefreshToken',
        ),
    ]
